language: php
php:
  - '7.0'

install:
  - composer self-update
  - make install
  
addons:
  code_climate:
    repo_token: 6acdeb1858c6e1fe8581daea18a61bc8d2bf52657cba041e38885353d5783c78

script: make lint test

after_script:
  - vendor/bin/test-reporter
